version: "3.8"
services:
  mongoservice:
    build: ./mongodb
    restart: always
    environment:
      MONGO_REPLICA_PORT: 27017
      MONGO_REPLICA_HOST: localhost
      MONGO_INITDB_ROOT_USERNAME: erhan
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: blog
    ports:
      - "27017:27017"
